# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://portal.cloud.hashicorp.com/vagrant/discover/bento/ubuntu-24.04
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  config.vm.hostname = 'network-lab'
  config.vm.define vm_name = 'net'

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e -x -u
    export DEBIAN_FRONTEND=noninteractive

    # Update packages and install required tools
    sudo apt-get update
    sudo apt-get install -y vim git cmake build-essential tcpdump tig socat bash-completion libpcap-dev bridge-utils ipcalc conntrack curl ca-certificates lsb-release gnupg

    # Install latest Docker (official recommended way)
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    sudo usermod -aG docker $USER

    # Install latest stable Golang (official installation)
    ARCH=$(uname -m)
    if [ "$ARCH" = "aarch64" ]; then
      GOARCH="arm64"
    else
      GOARCH="amd64"
    fi
    GO_LATEST=go1.24.4
    wget https://go.dev/dl/${GO_LATEST}.linux-${GOARCH}.tar.gz
    sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf ${GO_LATEST}.linux-${GOARCH}.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
    export PATH=$PATH:/usr/local/go/bin

    git clone https://github.com/baconYao/hiskio-course.git

    git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
    bash ~/.bash_it/install.sh -s

    # Install tcpterm
    go install github.com/sachaos/tcpterm@latest
  SHELL

  config.vm.network :private_network, ip: "172.17.8.222"
  config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end
end
